
export const SIGN_IN_START='SIGN_IN_START';
export const SIGN_IN_SUCCESS='SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL='SIGN_IN_FAIL';

export const SIGN_UP_START='SIGN_UP_START';
export const SIGN_UP_SUCCESS='SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL='SIGN_UP_FAIL';

export const POST_ITEM_START= 'POST_ITEM_START';
export const POST_ITEM_SUCCESS= 'POST_ITEM_SUCCESS'
export const POST_ITEM_FAIL= 'POST_ITEM_FAIL';

export const CHECK_ITEM_START= 'CHECK_ITEM_START';
export const CHECK_ITEM_SUCCESS= 'CHECK_ITEM_SUCCESS';
export const CHECK_ITEM_FAIL= 'CHECK_ITEM_FAIL';

export const DELETE_ITEM_START= 'DELETE_ITEM_START';
export const DELETE_ITEM_SUCCESS= 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL= 'DELETE_ITEM_FAIL';

export const GET_ITEM_START= 'GET_ITEM_START';
export const GET_ITEM_SUCCESS= 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAIL= 'GET_ITEM_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

